BG_COLOR = "#f0f2f5"
# Segoe UI is not available on many Linux installations and may resolve to a
# fallback without Cyrillic glyphs. Keep the UI font explicit and portable.
UI_FONT = "Noto Sans"
MONO_FONT = "DejaVu Sans Mono"
HEADER_COLOR = "#ffffff"
TEXT_COLOR = "#2c3e50"
ACCENT_COLOR = "#6c5ce7"
BUTTON_COLOR = "#6c5ce7"
BUTTON_HOVER = "#5b4bc4"

EXPIRED_COLOR = "#e57373"
WARNING_COLOR = "#ffd54f"
NORMAL_COLOR = "#81c784"
EXPIRED_TEXT = "#721c24"
WARNING_TEXT = "#856404"
NORMAL_TEXT = "#155724"

GRAPH_EXPIRED = "#f5c6cb"
GRAPH_WARNING = "#ffeeba"
GRAPH_NORMAL = "#27ae60"
SIDEBAR_COLOR = "#2c3e50"
SIDEBAR_TEXT_COLOR = "#ecf0f1"
CARD_BG_COLOR = "#ffffff"
CARD_BORDER_COLOR = "#e1e8ed"
CARD_TITLE_COLOR = "#7f8c8d"
CARD_VALUE_COLOR = "#2c3e50"
MCHD_COLOR = "#9b59b6"
MCHD_LIGHT_COLOR = "#f3e5f5"

CAL_EXPIRED_BG = "#e57373"
CAL_EXPIRED_FG = "#e57373"
CAL_WARNING_BG = "#ffd54f"
CAL_WARNING_FG = "#ffd54f"
CAL_NORMAL_BG = "#27ae60"
CAL_NORMAL_FG = "#ffffff"
CAL_TODAY_BG = "#155724"
CAL_TODAY_FG = "#ffffff"
