[project]
name = "certificate-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kanl", email = "106077541+kanl222@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
certificate-analyzer = "certificate_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
